//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityBooks
    {
        public string Title { get; set; }
        public string Aithors { get; set; }
        public string SupplierName { get; set; }
        public string StoreName { get; set; }
    }
}
