//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookshelves
    {
        public long ISBN { get; set; }
        public int idStore { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
